name: 'Lint code'
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: '9.1.1'
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: 'Install Deps'
        run: pnpm install
      - name: 'lint'
        run: pnpm lint
